MODEL:
  class_path: 'src.model.inception.InceptionNetworkWithDownsampling'
  KWARGS:
    num_out_channels: 96
    num_tests: 19
    num_bins: 100
TRAIN:
  LR_SCHEDULER:
    class_path: 'src.utils.CosineToConstantLR'
    KWARGS:
      T_max: 15000
      eta_min_divisor: 1.0
  CUDNN_BENCHMARK: True
  COMPILE: True
  STOPPER:
    class_path: 'src.utils.EarlyStopper'
    KWARGS:
      metric: 'val_loss'
      patience: 3
      delta: 0
  OPTIMIZER:
    class_path: 'src.optimizer.adammuon.AdamMuon'
    KWARGS:
      lr: 0.0037
  MIXED_PRECISION_SCALER:
    class_path: 'torch.amp.GradScaler'
    KWARGS: {}
  CRITERION:
    class_path: 'torch.nn.CrossEntropyLoss'
    KWARGS:
      ignore_index: -100
  KWARGS:
    epochs: 5
    device: 'cuda'
    metrics: []
    global_metrics:
      - class_path: 'src.metric.metric.topk_accuracy'

HYPERPARAMETER_SEARCH:
  # SEARCH_SPACE: False

  # # ------------- (un)comment to enable hyperparameter search -------------
  SEARCH_SPACE:
  #   DATASET:
  #     KWARGS:
  #       val_fold:
  #         SAMPLE_TYPE: 'ray.tune.choice'
  #         KWARGS:
  #           categories: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    MODEL:
      class_path: 'src.model.inception.InceptionNetworkWithDownsampling'
      KWARGS:
        num_out_channels:
          SAMPLE_TYPE: 'ray.tune.choice'
          KWARGS:
            categories: [32, 64, 96]
    TRAIN.OPTIMIZER:
      KWARGS:
        bin_smoothing_factor:
          SAMPLE_TYPE: 'ray.tune.choice'
          KWARGS:
            categories: [0.0, 0.1, 1.0, 10.0]
        lr:
          SAMPLE_TYPE: 'ray.tune.choice'
          KWARGS:
            categories: [0.001, 0.0037]
    DATALOADER:
      KWARGS:
        batch_size:
          SAMPLE_TYPE: 'ray.tune.choice'
          KWARGS:
            categories: [64, 128, 256]
  #       lr:
  #         SAMPLE_TYPE: 'ray.tune.loguniform'
  #         KWARGS:
  #           lower: 0.0005
  #           upper: 0.005
  # # ------------- (un)comment to enable hyperparameter search -------------

DATALOADER:
  class_path: 'torch.utils.data.DataLoader'
  KWARGS:
    batch_size: 128
    shuffle: True
    num_workers: 25
    pin_memory: True
    drop_last: True
    persistent_workers: True
    prefetch_factor: 6
DATASET:
  class_path: 'src.dataset.bloodtest_wfdb_dataset.BloodECGDataset'
  KWARGS:
    k_folds: 5
    val_fold: 0
    base_dir: '/dataset/physionet.org/files/mimic-iv-ecg-diagnostic/mimic-iv-ecg-diagnostic-electrocardiogram-matched-subset-1.0/'
    ecg_csv_path: '/home/stenheli/projects/physionet-challenge-2025/src/scripts/ecg_with_blood_24h.csv'
    blood_csv_path: '/home/stenheli/projects/physionet-challenge-2025/src/scripts/blood_with_ecg_24h.csv'
  TRAIN:
    KWARGS:
      split: 'train'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.NanToZero'
          - class_path: 'src.transform.transform.DropChannels'
          - class_path: 'src.transform.transform.AddGaussianNoise'
  VAL:
    KWARGS:
      split: 'val'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.NanToZero'
          - class_path: 'src.transform.transform.DropChannels'
          - class_path: 'src.transform.transform.AddGaussianNoise'