MODEL:
  class_path: 'src.model.inception.InceptionNetworkWithDownsampling'
  KWARGS: {}
TRAIN:
  LR_SCHEDULER:
    class_path: 'src.utils.CosineToConstantLR'
    KWARGS:
      T_max: 10000
      eta_min_divisor: 10.0
  CUDNN_BENCHMARK: False
  COMPILE: False
  STOPPER:
    class_path: 'src.utils.EarlyStopper'
    KWARGS:
      metric: 'val_loss'
      patience: 5
      delta: 0
  OPTIMIZER:
    class_path: 'torch.optim.AdamW'
    KWARGS:
      lr: 0.001
  MIXED_PRECISION_SCALER:
    class_path: 'torch.amp.GradScaler'
    KWARGS: {}
  CRITERION:
    class_path: 'torch.nn.BCEWithLogitsLoss'
  KWARGS:
    epochs: 50
    device: 'cuda:0'
    metrics: []
    global_metrics:
      - class_path: 'src.metric.metric.challenge_score'
      - class_path: 'src.metric.metric.aucroc'
      - class_path: 'src.metric.metric.aucprc'
HYPERPARAMETER_SEARCH:
  SEARCH_SPACE:
    TRAIN:
      OPTIMIZER:
        KWARGS:
          lr:
            SAMPLE_TYPE: 'ray.tune.grid_search'
            KWARGS:
              values: [5e-3, 2e-3, 1e-3, 5e-4, 2e-4, 1e-4]
DATALOADER:
  class_path: 'torch.utils.data.DataLoader'
  KWARGS:
    batch_size: 32
    shuffle: True
    num_workers: 4
    pin_memory: True
    pin_memory_device: 'cuda:0'
    prefetch_factor: 4
DATASET:
  class_path: 'src.dataset.hdf5_dataset.HDF5InMemoryDataset'
  KWARGS: {}
  TRAIN:
    KWARGS:
      hdf5_files:
        - '/data/physionet-challenge-2025/code15/exams_part0.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part1.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part2.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part3.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part4.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part5.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part6.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part7.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part8.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part9.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part10.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part11.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part12.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part13.hdf5'
      labels_csv: '/data/physionet-challenge-2025/code15/code15_chagas_labels/code15_chagas_labels.csv'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.CenterCrop'
            KWARGS:
              size: 2700
          - class_path: 'src.transform.transform.HighPassButterworth'
          - class_path: 'src.transform.transform.SoftNormalize'
  VAL:
    KWARGS:
      hdf5_files:
        - '/data/physionet-challenge-2025/code15/exams_part14.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part15.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part16.hdf5'
        - '/data/physionet-challenge-2025/code15/exams_part17.hdf5'
      labels_csv: '/data/physionet-challenge-2025/code15/code15_chagas_labels/code15_chagas_labels.csv'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.CenterCrop'
            KWARGS:
              size: 2700
          - class_path: 'src.transform.transform.HighPassButterworth'
          - class_path: 'src.transform.transform.SoftNormalize'
          