MODEL:
  class_path: 'src.model.inception_ensemble.InceptionEnsemble'
  KWARGS:
    weights_dir: 'src/weights'
    inception_kwargs:
      num_out_channels: 96
TRAIN:
  LR_SCHEDULER:
    class_path: 'src.utils.CosineToConstantLR'
    KWARGS:
      T_max: 10000
      eta_min_divisor: 2.0
  CUDNN_BENCHMARK: False
  COMPILE: False
  STOPPER:
    class_path: 'src.utils.EarlyStopper'
    KWARGS:
      metric: 'val_loss'
      patience: 5
      delta: 0
  OPTIMIZER:
    class_path: 'src.optimizer.adammuon.AdamMuon'
    KWARGS:
      lr: 0.00001
  MIXED_PRECISION_SCALER:
    class_path: 'torch.amp.GradScaler'
    KWARGS: {}
  CRITERION:
    class_path: 'torch.nn.BCEWithLogitsLoss'
  KWARGS:
    epochs: 1
    device: 'cuda'
    metrics: []
    global_metrics:
      - class_path: 'src.metric.metric.challenge_score'
      - class_path: 'src.metric.metric.aucroc'
      - class_path: 'src.metric.metric.aucprc'
HYPERPARAMETER_SEARCH:
  SEARCH_SPACE: false

DATALOADER:
  class_path: 'torch.utils.data.DataLoader'
  KWARGS:
    batch_size: 32
    shuffle: true
    num_workers: 2
    drop_last: false
    persistent_workers: True
    prefetch_factor: 2
DATASET:
  class_path: 'src.dataset.wfdb_dataset.WFDBDataset'
  KWARGS:
    k_folds: 5
    val_fold: 0
  TRAIN:
    KWARGS:
      root_dir: '/dataset/GeorgeMoodyChallenge2025/'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.RandomCrop'
            KWARGS:
              size: 2700
          - class_path: 'src.transform.transform.NanToZero'
          - class_path: 'src.transform.transform.DropChannels'
  VAL:
    KWARGS:
      root_dir: '/dataset/GeorgeMoodyChallenge2025/'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.CenterCrop'
            KWARGS:
              size: 2700
          - class_path: 'src.transform.transform.NanToZero'
          - class_path: 'src.transform.transform.DropChannels'