MODEL:
  class_path: 'src.model.inception.InceptionNetworkWithDownsampling'
  KWARGS:
    num_out_channels: 32
LOAD_MODEL:
  weights_path: '/home/stenheli/projects/physionet-challenge-2025/sandbox/checkpoint_epoch_3.pt'
  drop_last_fc: True
TRAIN:
  LR_SCHEDULER:
    class_path: 'src.utils.CosineToConstantLR'
    KWARGS:
      T_max: 10000
      eta_min_divisor: 1.0
  CUDNN_BENCHMARK: True
  COMPILE: True
  STOPPER:
    class_path: 'src.utils.EarlyStopper'
    KWARGS:
      metric: 'val_loss'
      patience: 7
      delta: 0
  OPTIMIZER:
    class_path: 'src.optimizer.adammuon.AdamMuon'
    KWARGS:
      lr: 0.001
  MIXED_PRECISION_SCALER:
    class_path: 'torch.amp.GradScaler'
    KWARGS: {}
  CRITERION:
    class_path: 'torch.nn.BCEWithLogitsLoss'
  KWARGS:
    epochs: 30
    device: 'cuda'
    metrics: []
    global_metrics:
      - class_path: 'src.metric.metric.challenge_score'
      - class_path: 'src.metric.metric.aucroc'
      - class_path: 'src.metric.metric.aucprc'
HYPERPARAMETER_SEARCH:

  # SEARCH_SPACE: False

  # ------------- (un)comment to enable hyperparameter search -------------
  SEARCH_SPACE:
    LOAD_MODEL:
      weights_path:
        SAMPLE_TYPE: 'ray.tune.grid_search'
        KWARGS:
          values:
            - '/home/stenheli/projects/physionet-challenge-2025/sandbox/weights/load_and_train_2025-08-13_20-23-21_val_fold_0_checkpoint_000005.pt'
            - '/home/stenheli/projects/physionet-challenge-2025/sandbox/weights/load_and_train_2025-08-13_20-23-21_val_fold_1_checkpoint_000004.pt'
            - '/home/stenheli/projects/physionet-challenge-2025/sandbox/weights/load_and_train_2025-08-13_20-23-21_val_fold_2_checkpoint_000001.pt'
            - '/home/stenheli/projects/physionet-challenge-2025/sandbox/weights/load_and_train_2025-08-13_20-23-21_val_fold_3_checkpoint_000001.pt'
            - '/home/stenheli/projects/physionet-challenge-2025/sandbox/weights/load_and_train_2025-08-13_20-23-21_val_fold_4_checkpoint_000004.pt'
            - '/home/stenheli/projects/physionet-challenge-2025/sandbox/checkpoint_epoch_3.pt'
    DATASET:
      KWARGS:
        val_fold:
          SAMPLE_TYPE: 'ray.tune.grid_search'
          KWARGS:
            values: [0, 1, 2, 3, 4]

DATALOADER:
  class_path: 'torch.utils.data.DataLoader'
  KWARGS:
    batch_size: 128
    shuffle: True
    num_workers: 16
    pin_memory: True
    drop_last: False
    persistent_workers: True
    prefetch_factor: 2
DATASET:
  class_path: 'src.dataset.wfdb_dataset.WFDBDataset'
  KWARGS:
    k_folds: 5
    val_fold: 0
    reweighting_csv: '/dataset/GeorgeMoodyChallenge2025/code15/patient_ids_both_positive_and_negative_chagas.csv'
  TRAIN:
    KWARGS:
      root_dir: '/dataset/GeorgeMoodyChallenge2025/'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.NanToZero'
          - class_path: 'src.transform.transform.DropChannels'
          - class_path: 'src.transform.transform.CropZeroPadded'
          - class_path: 'src.transform.transform.RandomCrop'
            KWARGS:
              size: 800
          - class_path: 'src.transform.transform.Normalize'
    KWARGS:
      root_dir: '/dataset/GeorgeMoodyChallenge2025/'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.NanToZero'
          - class_path: 'src.transform.transform.DropChannels'
          - class_path: 'src.transform.transform.CropZeroPadded'
          - class_path: 'src.transform.transform.CenterCrop'
            KWARGS:
              size: 800
          - class_path: 'src.transform.transform.Normalize'
