MODEL:
  class_path: 'src.model.inception.InceptionNetworkWithDownsampling'
  KWARGS:
    num_out_channels: 96
LOAD_MODEL:
  weights_path: '/home/stenheli/projects/physionet-challenge-2025/sandbox/checkpoint_epoch_2.pt'
  drop_last_fc: True
TRAIN:
  LR_SCHEDULER:
    class_path: 'src.utils.CosineToConstantLR'
    KWARGS:
      T_max: 10000
      eta_min_divisor: 2.0
  CUDNN_BENCHMARK: True
  COMPILE: True
  STOPPER:
    class_path: 'src.utils.EarlyStopper'
    KWARGS:
      metric: 'val_loss'
      patience: 2
      delta: 0
  OPTIMIZER:
    class_path: 'src.optimizer.adammuon.AdamMuon'
    KWARGS:
      lr: 0.001
  MIXED_PRECISION_SCALER:
    class_path: 'torch.amp.GradScaler'
    KWARGS: {}
  CRITERION:
    class_path: 'torch.nn.BCEWithLogitsLoss'
  KWARGS:
    epochs: 30
    device: 'cuda'
    metrics: []
    global_metrics:
      - class_path: 'src.metric.metric.challenge_score'
      - class_path: 'src.metric.metric.aucroc'
      - class_path: 'src.metric.metric.aucprc'
HYPERPARAMETER_SEARCH:

  # SEARCH_SPACE: False

  # # ------------- (un)comment to enable hyperparameter search -------------
  SEARCH_SPACE:
    DATASET:
      KWARGS:
        val_fold:
          SAMPLE_TYPE: 'ray.tune.choice'
          KWARGS:
            categories: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  #   MODEL:
  #     class_path: 'src.model.inception.InceptionNetworkWithDownsampling'
  #     KWARGS:
  #       num_out_channels:
  #         SAMPLE_TYPE: 'ray.tune.choice'
  #         KWARGS:
  #           categories: [32, 64, 128]
  #   TRAIN.OPTIMIZER:
  #     KWARGS:
  #       lr:
  #         SAMPLE_TYPE: 'ray.tune.loguniform'
  #         KWARGS:
  #           lower: 0.0005
  #           upper: 0.005
  # # ------------- (un)comment to enable hyperparameter search -------------

DATALOADER:
  class_path: 'torch.utils.data.DataLoader'
  KWARGS:
    batch_size: 64
    shuffle: True
    num_workers: 16
    pin_memory: True
    drop_last: False
    persistent_workers: True
    prefetch_factor: 2
DATASET:
  class_path: 'src.dataset.wfdb_dataset.WFDBDataset'
  KWARGS:
    k_folds: 10
    val_fold: 0
  TRAIN:
    KWARGS:
      root_dir: '/dataset/GeorgeMoodyChallenge2025/'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.RandomCrop'
            KWARGS:
              size: 2700
          # - class_path: 'src.transform.transform.HighPassButterworth'
          # - class_path: 'src.transform.transform.SoftNormalize'
          - class_path: 'src.transform.transform.DropChannels'
          - class_path: 'src.transform.transform.Normalize'
          - class_path: 'src.transform.transform.RandomMultiply'
  VAL:
    KWARGS:
      root_dir: '/dataset/GeorgeMoodyChallenge2025/'
    TRANSFORM:
      class_path: 'src.transform.transform.ComposedTransform'
      KWARGS:
        transform_config:
          - class_path: 'src.transform.transform.CenterCrop'
            KWARGS:
              size: 2700
          # - class_path: 'src.transform.transform.HighPassButterworth'
          # - class_path: 'src.transform.transform.SoftNormalize'
          - class_path: 'src.transform.transform.DropChannels'
          - class_path: 'src.transform.transform.Normalize'